---
HOSTS:
  centos7-64-1:
    hypervisor: docker
    image: centos:7 
    platform: el-7-x86_64
    roles:
      - agent
    docker_preserve_image: true
    docker_cmd: '["/sbin/init"]'
CONFIG:
  type: foss 
  log_level: verbose
 # log_level: debug
ssh:
  auth_methods: 
   - password  
  user: root
  password: root
